### ISSUE TITLE
Meeting 2023.4.15

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/petal#2]
1. 插件商店迁移到集市，文件方式还是使用目前技术的方案 https://github.com/siyuan-note/siyuan/issues/8042 https://github.com/siyuan-note/siyuan/issues/8043
2. FileApi兼容性移除 https://github.com/siyuan-note/petal/issues/5
3. 集市切换后，插件开发者需要支持其仓库更新到集市方案里，老的工程就归档了。需要通知社区和群 https://github.com/siyuan-note/petal/issues/6
4. 内核接口增加，用于插件系统读取插件文件 https://github.com/siyuan-note/siyuan/issues/8044
5. 数据同步时插件的加载时机和同步冲突的问题
6. API初步框架完成机制建立 https://github.com/siyuan-note/petal/issues/7

**Comment by 88250** [comment]
> 5. 数据同步时插件的加载时机和同步冲突的问题

这个暂时不建立任务了，先解决其他任务。
