### ISSUE TITLE
Add some `Protyle` methods to the plugin API

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/petal#21]
----问题1
背景: 
想使用plugin.addCommand添加命令,按下快捷键后对光标所在块进行处理,我使用了editorCallback,想知道在其中如何获取当前光标所在块元素

--- 问题2
建议把源码里面 getEditorRange  hasClosestBlock  hasClosestByAttribute 等函数也开放给插件使用, 避免造轮子

**Comment by Vanessa219** [comment]
通过问题2的 API `hasClosestBlock` 就可以解决问题1了。需要的话我先把 hasClosestBlock 开放出去。由于 getEditorRange 会根据使用场景进行判断，如果光标不在 editor 中会将其设置到第一个块中，从而改变光标的原有位置，就先不放出去了。

**Comment by iamqiz** [comment]
@Vanessa219 
问题1 解决了(用的Zuoqiu-Yingyi的代码),然后我想实现把段落块转换为列表块,之前在思源源码里调用 turnsIntoOneTransaction 加 type:Blocks2ULs ,很方便,但没开放给插件用,建议开放 , 再加上个 focusBlock  .
话说能不能让插件无缝对接思源源码,即直接使用思源源码里任意函数而不需要特意开放?

**Comment by Vanessa219** [comment]
我抽空整理一下吧。为了安全性思源源码目前不能直接使用，有需求提就好了，我们会尽快完善的。

**Comment by Vanessa219** [comment]
* turnIntoOneTransaction
* turnIntoTransaction
* updateTransaction
* updateBatchTransaction
* getRange
* hasClosestBlock
* focusBlock
