### ISSUE TITLE
打开插件管理页面速度太慢

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/petal#22]
设置>集市>已下载>插件  加载太慢, 尽管我只有5个插件,但加载了4秒左右

由于这个原因,导致查看某个插件的readme时效率很低,
因此建议,在每个插件的菜单中加入新菜单项"打开插件主页", 如下图
![Snipaste_环境返回_2023-11-29__10-46-15](https://github.com/siyuan-note/petal/assets/48077521/e2172b4d-c70e-4ce1-8d26-3b2539e6b435)

**Comment by 88250** [comment]
暂时没有办法了，加载插件需要走网络检查更新。

**Comment by iamqiz** [comment]
@88250  我发现加载慢的原因了, 是因为后端会计算插件目录的大小, 
![Clip_2024-04-28_21-09-36](https://github.com/siyuan-note/petal/assets/48077521/b1aca680-1c89-45f0-9009-3775bd0c1687)

100MB的插件nodejs目录,大概耗时3秒
优化方式有下面几种
1. 云端解压计算install size ? 利用github的action? 从而不用占用自己服务器的资源?
2. 打开readme时再计算大小
3. 增加一个 "统计本地已安装包的信息",点击之后才会计算大小
4. 增加一个本地 比如 data/storage/bazaars-info.json , 在安装和更新插件时计算大小,将size保存到文件里,在计算目录size时先从该文件读取size,没有的话再计算size, 计算完再更新该文件

我大致实现了方式4,  但3感觉更好
D大怎么看?

**Comment by 88250** [comment]
似乎方案1比较优秀，稍后我看看如何改进，谢谢。
