### ISSUE TITLE
Improve Global.Lute type

### ISSUE THREAD

**Issue by etchnight** [siyuan-note/petal#23]
原来的标注
```ts
export interface Global {
    Lute: Lute ;
}
```
![捕获](https://github.com/siyuan-note/petal/assets/39119983/ceadfe0b-12d3-4f88-bd32-99ff3fc8272b)

似乎应该更改为：
```ts
export interface Global {
    Lute: typeof Lute ;
}
```
![捕获2](https://github.com/siyuan-note/petal/assets/39119983/8c24d756-fb7a-4f6f-b6c5-7759b49cb45e)

**Comment by Vanessa219** [comment]
已经标明了 static
<img width="347" alt="image" src="https://github.com/siyuan-note/petal/assets/970828/6fdc50a5-ed6b-4e5c-8806-69f8253e2185">

**Comment by etchnight** [comment]
这个地方没有问题，我指的是全局上Lute的类型注解，`siyuan.d.ts`中第68行

![360截图18141215235619](https://github.com/siyuan-note/petal/assets/39119983/8dc6704f-9c2e-4fd3-b207-f6fe3643dbc9)

```ts
export interface Global {
    Lute: Lute ;//应改为 typeof Lute
}
```

原来的标注似乎是指`window.Lute`是class Lute的实例，但其并没有实例化

**Comment by Vanessa219** [comment]
#88888888
