### ISSUE TITLE
列表api

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/petal#26]
我想实现把当前块作为相邻列表的子元素
如下图所示

当前:
![Clip_2024-03-23_23-28-29](https://github.com/siyuan-note/petal/assets/48077521/14567002-f453-4cc0-aadd-357377b5f5cc)

期望实现:
![Clip_2024-03-23_23-28-43](https://github.com/siyuan-note/petal/assets/48077521/e6180b75-8c99-4608-bbc4-0aea8d87000d)

我的想法是把当前c块转变为NodeListItem ,然后把它appendChild到相邻的NodeList里
这两个步骤我感觉用目前的插件api不好实现
能不能增加这样的api?

**Comment by iamqiz** [comment]
同理,希望能把思源里的块设计为单独的class,然后通过类方法来实现该类块的操作,
比如 以列表块为例,实现上述的功能
```
let para_element= <获取当前光标下的NodeParagraph元素>
let list_element= <获取相邻块的NodeList元素>
let listitem=SYList.createListItem(para_element)
let listObj=new SYList(list_element)
listObj.appendChild(listitem)
```

**Comment by Vanessa219** [comment]
可以用 Lute 来创建空列表，自己封装一下吧。

**Comment by iamqiz** [comment]
@Vanessa219 解决了, 插件可以用lute很nice
遗憾之一就是没文档,源码里也没对API作用的注释, 我是看了源码才知道

**Comment by Vanessa219** [comment]
哈哈，有空可以 PR 下
