### ISSUE TITLE
Add `dialog` object to `Setting` property

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/petal#28]
![Clip_2024-04-25_17-13-04](https://github.com/siyuan-note/petal/assets/48077521/a8ebb36c-4d92-4b7c-b4c9-0b204a7c44e4)

目前的痛点: 对话框没有id,只能通过class等方式获取, 不知道是不是唯一的

**Comment by Vanessa219** [comment]
加一个 dialog 是否够用了？
<img width="461" alt="image" src="https://github.com/siyuan-note/petal/assets/970828/9d4aeff2-c674-468e-b717-7219029df0d5">

**Comment by iamqiz** [comment]
@Vanessa219 都加上吧, setting对象里, 和回调函数参数里

**Comment by Vanessa219** [comment]
自身的属性，回调里面就不加了。
