### ISSUE TITLE
插件protyleOptions.toolbar影响斜杠菜单

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/petal#30]
通过 插件protyleOptions.toolbar 把一些工具(比如行内公式)禁用后, 会影响斜杠菜单,导致在斜杠菜单中调用行内公式会报错

原因是执行斜杠菜单中部分命令时(比如行内公式),会调用 protyle.toolbar.element 中的命令,而这些元素因为被禁用了所以不存在,因而报错 ,如下
https://github.com/siyuan-note/siyuan/blob/84819beaf7f5bdf237421edb3e98830d6d457ecd/app/src/protyle/hint/index.ts#L658

另外,插件的protyleOptions.toolbar属性设计有点问题,它规定了整个toolbar有哪些工具,而不能以增量/替换/删除等方式来微调工具栏, 如果我想增加一个工具,那么需要把所有默认的工具(即思源自带的工具,如粗体,斜体,下划线等)也要声明一边,这有点多此一举了,如果思源未来增加了新的默认工具,那么插件里需要同步增加,才能显示出新的默认工具, 这就麻烦了

考虑到上面两个问题,我觉得可以如下改进

a. 增加一个插件属性,用于获取所有的默认toolbar工具,

b. 增加一个选项 hidden ,用于隐藏(而非删除)指定默认工具
,比如
```
        this.protyleOptions = {
            toolbar: [
                {
                    name: "inline-math",
                    hidden: true
                }
            ]
```
更新:  我改用css display:none来隐藏(而不是删除)默认工具即可绕过问题1
改进a还是有必要的
改进b 暂时可以不考虑

**Comment by Vanessa219** [comment]
可以使用 `protyle.options.toolbar` 来获取

**Comment by Vanessa219** [comment]
那先写死吧，这个应该不会动了，动的话估计也是用插件，插件的话我也获取不到。
