### ISSUE TITLE
这里的类型是手写的吗

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/petal#31]
siyuan 本体也是 ts 项目，我认为直接从那个项目生成 .d.ts 文件更好

**Comment by Vanessa219** [comment]
这个只是插件部分，需要剥离开来。

**Comment by 2234839** [comment]
我想的是从siyuan项目添加一个ts文件，该文件负责引入插件相关类型，然后编译该文件到dts


优势在于类型保持同步，现在是有些类型这个项目比siyuan还写得好，但有些类型这里有缺失

**Comment by Vanessa219** [comment]
是拷贝过去的，不应该呀，发现问题的话可以 PR。
自动的话好像问题有点多，有精力的话可以帮忙探索探索。
