### ISSUE TITLE
请问优化排版这个事件能捕获到么？

### ISSUE THREAD

**Issue by feng-yifan** [siyuan-note/petal#35]
可以的话，名称是什么？

**Comment by Vanessa219** [comment]
目前没有，捕获场景和时机是？

**Comment by feng-yifan** [comment]
> 目前没有，捕获场景和时机是？

嵌入一些自定义的排版规则，增强默认排版。

**Comment by Vanessa219** [comment]
看了一下代码，这个接口是后台推送的，没有切入点，可以使用 `open-menu-breadcrumbmore` 单独加一个菜单。
